#!/bin/bash
if [ ! -d "/host/mysql" ]; then
   mysql_install_db --user=mysql --datadir=/host/mysql
fi
/usr/sbin/mysqld --basedir=/usr --datadir=/host/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/host/mysql-error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
